name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Log in to DockerHub
        run: echo $token | docker login --username divoolej --password-stdin
        env:
          token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -f docker/web.Dockerfile -t divoolej/private:mapy-nageografiepl-be .

      - name: Push Docker image
        run: docker push divoolej/private

      - name: Log out of DockerHub
        run: docker logout
